<p>
<img class="img_contact" src="/img/contact.jpg">
</p>

<b><?=$message; ?></b>

<form method="post" enctype="multipart/form-data">
    Name : <br/><input type="text" name="name" size="26" value="<?=$form->getName(); ?>" /> <br/><br/>
    Email : <br/><input type="email" name="email" size="26" value="<?=$form->getEmail(); ?>"/> <br/><br/>
    Message : <br/>
    <textarea name="message" cols="130" rows="10"><?=$form->getMessage(); ?></textarea> <br/><br/>
    <input type="submit" class="send" value="Send">

</form>